application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "support@applogi.co"
  authorization_token: "test_auth_token"
  timeout_ms: 1000
